# docker/docker-compose.yml
version: "3.7"
services:
  db:
    image: postgres:12.4
    restart: always
    hostname: db.docker.local
    volumes:
      - ./containers/db/etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./data/db/data:/pgdata
    ports:
      - target: 5432
        published: ${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /pgdata
    networks:
      - private_network

  php:
    build:
      context: ./containers/php
    hostname: php.docker.local
    volumes:
      - ../src:/opt/dim
    depends_on:
      - db
    ports:
      - target: 9001
        published: ${XDEBUG_PORT}
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=12.4
    networks:
      - private_network

  nginx:
    image: nginx
    hostname: nginx.docker.local
    volumes:
      - ./containers/nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./containers/nginx/etc/nginx/sites-available:/etc/nginx/sites-available
      - ./containers/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../src:/opt/dim
    depends_on:
      - php
    ports:
      - target: 80
        published: ${NGINX_PORT}
    networks:
      - private_network

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
#      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_LISTEN_PORT: 80
#    volumes:
#      - ./data/pgadmin:/var/lib/pgadmin
#    links:
#      - "db:pgsql-server"
#    networks:
#      - private_network

networks:
  private_network:

#volumes:
#  pgdata:
#  pgadmin-data:
